version: "3"
services:
  react-app:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: on-failure
    ports:
      - "8080:3000"
    volumes:
      - /app/node_modules
      - .:/app
